version: '3'

services:
  plc-service-a:
    build:
      context: .
      dockerfile: ./PLC.ServiceA/Dockerfile
    ports:
      - 5002:80

  plc-service-b:
    build:
      context: .
      dockerfile: ./PLC.ServiceB/Dockerfile
    ports:
      - 5003:80

  regulator:
    build:
      context: .
      dockerfile: ./Regulator/Dockerfile
    ports:
      - 5000:80
  
  rabbit-mq:
    image: masstransit/rabbitmq:3
    ports:
    - 15672:15672
    - 5672:5672
  
  redis:
    image: redis:6.2.6-alpine3.15
    ports:
    - 6000:6379