version: '3'

services:
  plc-service-a:
    build: ./PLC.ServiceA
    ports:
      - 5002:80

  plc-service-b:
    build: ./PLC.ServiceB
    ports:
      - 5003:80

  regulator:
    build: ./Regulator
    ports:
      - 5000:80
