
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - PLC.ServiceA
      - Contrants
pr:
  branches:
    include:
      - main
  paths:
    include:
      - PLC.ServiceA/*

pool: 'Default'

steps:
- template: ../templates/create-docker.yml
  parameters:
    dockerfilePath: PLC.ServiceA/Dockerfile
    dockerTag: $(gitBranch == "main") ? "latest" : $(Buildnumber) 
